################################################################
# Docker configuration backend
################################################################

# Docker configuration backend
providers:
  docker:
    exposedByDefault: false
entryPoints:
  web:
    address: ":80"
# API and dashboard configuration
api:
  insecure: true